//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ID_Client { get; set; }
        public string Name_Client { get; set; }
        public string Surname_Client { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Admin_Right { get; set; }
    }
}
